// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/volcengine/vei-driver-sdk-go/pkg/contracts"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/volcengine/vei-driver-sdk-go/extension/requests"
)

// Discovery is an autogenerated mock type for the Discovery type
type Discovery struct {
	mock.Mock
}

// Discover provides a mock function with given fields: ctx, param, deviceCh
func (_m *Discovery) Discover(ctx context.Context, param *requests.DiscoveryParameter, deviceCh chan<- *contracts.Device) {
	_m.Called(ctx, param, deviceCh)
}

// NewDiscovery creates a new instance of Discovery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscovery(t interface {
	mock.TestingT
	Cleanup(func())
}) *Discovery {
	mock := &Discovery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
