// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/edgexfoundry/device-sdk-go/v2/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// Discovery is an autogenerated mock type for the Discovery type
type Discovery struct {
	mock.Mock
}

// Discover provides a mock function with given fields:
func (_m *Discovery) Discover() []models.DiscoveredDevice {
	ret := _m.Called()

	var r0 []models.DiscoveredDevice
	if rf, ok := ret.Get(0).(func() []models.DiscoveredDevice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DiscoveredDevice)
		}
	}

	return r0
}

type mockConstructorTestingTNewDiscovery interface {
	mock.TestingT
	Cleanup(func())
}

// NewDiscovery creates a new instance of Discovery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDiscovery(t mockConstructorTestingTNewDiscovery) *Discovery {
	mock := &Discovery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
